<?php

return [
    'title-tab' => 'Cooperativa digital',
    'title'     => 'Cooperativa digital agromakers ecomakers',
    'sub-title' => 'Tejer confianza entre todos : los productores, la biodiversidad, el climá, los consumidores, los investigadores, las instituciones públicas, privadas, espirituales, las asociaciones, las empresas...',
    'content-title'   => 'Una oportunidad ecológica y cooperativa',
    'content-text'    => 'El mercado del futuro tendrá que ser ecológico. En realidad es una oportunidad para los pequeños productores. La falta de recursos y de insumos costosos se cambia en una oportunidad para cooperar con la naturaleza. Los insectos, las lombrices, las bacterias y los hongos del suelo, son amigos de las plantas, transforman las moléculas que se encuentran en alta cantidad en el ambiente para que se vuelvan accesibles para las plantas. En vez de arar penosamente la tierra con la fuerza de los brazos o con una maquina que cuesta, consume gasolina y liberar carbono podemos dejarnos ayudar por la vida del suelo para que haga su trabajo. Como siempre lo ha hecho en la selva .  La selva que produce, almacena carbono sin que tengamos que aportar nada.  En vez de hechar veneno a esta tierra para eliminar las plagas podemos dejarnos ayudar por las avispas o parasitoides que comen a las plagas, o por las plantas repelentes. El principio de la agroecología, la cooperación entre los seres vivos, es teóricamente más eficiente que los principios de la depredación y competencia, que gastan energía. Permite más producción con menos trabajo y menos destrucción. Valora la diversidad, coordinando las funciones ecológicas que están a disposición en la naturaleza y que nuestros ancestros cuidaban. Todos podemos aprovechar, desde el campesino mismos hasta el ciudadano, que puede comprar al vecino campesino, o que tiene un pequeño espacio para sus proprias plantas. Lo único que hace falta es que todos encuentren en un lugar y comparten infromación, productos y servicios. Existen varias asociaciones separadas que hacen un trabajo esencial para construir de manera agro-ecologica. Con la red internet y el código abierto, el principio de cooperación agroeoclógica se puede ahora extender su eficiencia más alla de la asociaciones. Tejer entre las diferentes asociaciones, con los consumidores, los científicos o universitarios, y todos los participantes del sistema alimentario. Es el modelo de producción del futuro donde todos contribuyen en red y reciben retribución justa. Los señales de fracaso de los otros modelos de producción están ahora muy evidentes. Especialmente en esta época de crisis nos damos cuenta de nuestra fragilidad. No podemos dejar que pase esta oportunidad de cooperar entre los humanos y entre las especies organisando todos nuestros saberes, sean geneticos, de tradiciones, de culturas o de ciencia moderna. Facilitar y simplificar esta organización es el propósito de la cooperativa digital agromakers.',
    'content-title0'   => 'Agromakers-ecomakers',
    'content-text0'    => 'Un espacio de cooperación donde uno puede entrar como persona o organización y recibir retribución justa dependiendo del cambio de huella ecológica y social que aporte su actividad. Los indicadores de sostenibilidad serian definidos por un comité democrático, apoyado de académicos especialistas.',
    //'content-title2'   => 'La solución digital y tecnológica abierta',
    //'content-text2'    => 'La cooperativa digital agromakers es un lugar donde cada uno podrá mejorar sus practicas y recibir recompensa justa por su aporte a la sostenibilidad. Si es campesino. En el menú nosotros podrán encontrar a todos los actores de la agro-ecología cerca de su casa, los productores, la academia, las instituciones públicas, las asociaciones ecológicas y agro-ecológicas, los sitios de agro-turismo, las empresas agro-ecológicas cerca de ustedes. En el menú recursos encontrarán herramientas código abierto para construir uno mismo o con la ayuda de artesanos o de fablabs herramientas para la agro-ecológica de pequeña escala desde herramientas para el cultivo hasta estaciones meteorológicas o herramientas para la venta de sus productos. En recursos encontrarán los sitios de aprendizaje, talleres, eventos, y manuales. Encontraran también en recursos los aplicativos para la agro-ecología. En particular nuestra app miCampoApp que les permitirá fácilmente con botones tomar datos de su cultivo para la certificación, la logística o la evaluación de prácticas proprias. Encontrarán también en este menú recursos, los sitios de e-commerce para poder vender sus productos. En el menú eventos será la información de los seminarios webminars, encuentros, mercados campesinos relacionados con la agro-ecología. Esta plataforma es de ustedes, con el appMiCampoApp podrán completar la infromación crear blogs para informar. La plataforma esta financiada por el laboraotio mixto internacional Bio_Inca que reúne a la Universidad de los Andes, La poncificia Univeridad católica del Ecuador y el IRD, instituto Francés de investigación para el desarrollo. Después con el tiempo, siendo una cooperativa, la plataforma sera financiada por los usuarios. Retribuirá automáticamente los que con su actividad contribuyen a la sostenibilidad. Se basará en indicadores de sostenibilidad según las reglas definidas de manera democrática entre los usuarios. El objetivo concretó es la reversión de nuestra huella ecológica hacia el clima y hacia la vida en general. ',
    //'permaculture-title'    => 'La permacultura como principio',
    //'permaculture-text'    => 'La permacultura es un sistema de principios de diseño agrícola y económico, político y social basado en los patrones y las características del ecosistema natural.',
    //'openclim-title'    => 'La agricultura inteligente accesible para los pequeños productores',
    //'openclim-text'    => 'Una estación meteolologíca bajo costo codigo abierto conectada a la red por 2G trabajando a traves del 80% del territorio Colombiano para recibir alertas y apoyo a la decision de agromakers'
    'content-title__2'  => 'Para los agricultuores',
    'content-text__2'   => 'La cooperativa digital agromakers es un lugar donde cada uno podrá mejorar sus practicas y recibir recompensa justa por su aporte a la sostenibilidad.',
    'content-item-1__2' => 'Podrán encontrar a todos los actores de la agro-ecología cerca de su casa como los productores, la academia, las instituciones públicas, las asociaciones ecológicas y agro-ecológicas, los sitios de agro-turismo y las empresas agro-ecológicas.',
    'content-item-2__2' => 'Contarán con recursos o herramientas de código abierto para construir uno mismo o con la ayuda de artesanos o de fablabs herramientas para la agro-ecológica.',
    'content-item-3__2' => 'Podrán participar en sitios de aprendizaje, talleres, eventos, y contara con manuales.',
    'content-item-4__2' => 'Tendrán la oportunidad de contar con diversas certificaciones a base de recolectar información.',
    'content-item-5__2' => 'Mediante las herramientas digitales compartiran información de todo tipo enter la comunidad.',
];
